# Generated by Django 5.1.3 on 2024-11-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='baby_Admission',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('hosp_number', models.CharField(max_length=50, unique=True)),
                ('gestational_age', models.DecimalField(decimal_places=1, max_digits=4)),
                ('birth_weight', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
    ]
