# Generated by Django 5.1.3 on 2024-11-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0002_baby_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tfi_per_hour', models.FloatField()),
                ('lipid_volume_hourly', models.FloatField()),
                ('total_protein_g', models.FloatField()),
                ('total_protein_kcal', models.FloatField()),
                ('protein_kcal_per_kg_day', models.FloatField()),
                ('dextrose_kcal_per_kg_day', models.FloatField()),
                ('total_calories', models.FloatField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_records', to='nutra.baby_admission')),
            ],
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
