# Generated by Django 5.1.3 on 2024-12-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0004_babyresults_delete_nutritioncalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby_admission',
            name='hosp_number',
            field=models.CharField(max_length=50),
        ),
    ]
