# Generated by Django 5.1.3 on 2024-12-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0005_alter_baby_admission_hosp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyresults',
            name='current_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='babyresults',
            name='percent_weight_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
